//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManejoErroresSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Errores
    {
        public System.DateTime Execution_Date { get; set; }
        public string User_Name { get; set; }
        public Nullable<int> Error_Number { get; set; }
        public Nullable<int> Error_Line { get; set; }
        public Nullable<int> Error_Severity { get; set; }
        public Nullable<int> Error_State { get; set; }
        public string Error_Procedure { get; set; }
        public string Error_Message { get; set; }
    }
}
