USE [master]
GO
/****** Object:  Database [Demo_Indices]    Script Date: 25/04/2023 01:38:56 p. m. ******/
CREATE DATABASE [Demo_Indices]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Demo_Indices', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Demo_Indices.mdf' , SIZE = 860160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Demo_Indices_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Demo_Indices_log.ldf' , SIZE = 532480KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Demo_Indices] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Demo_Indices].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Demo_Indices] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Demo_Indices] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Demo_Indices] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Demo_Indices] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Demo_Indices] SET ARITHABORT OFF 
GO
ALTER DATABASE [Demo_Indices] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Demo_Indices] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Demo_Indices] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Demo_Indices] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Demo_Indices] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Demo_Indices] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Demo_Indices] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Demo_Indices] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Demo_Indices] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Demo_Indices] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Demo_Indices] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Demo_Indices] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Demo_Indices] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Demo_Indices] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Demo_Indices] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Demo_Indices] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Demo_Indices] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Demo_Indices] SET RECOVERY FULL 
GO
ALTER DATABASE [Demo_Indices] SET  MULTI_USER 
GO
ALTER DATABASE [Demo_Indices] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Demo_Indices] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Demo_Indices] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Demo_Indices] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Demo_Indices] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Demo_Indices] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Demo_Indices', N'ON'
GO
ALTER DATABASE [Demo_Indices] SET QUERY_STORE = ON
GO
ALTER DATABASE [Demo_Indices] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Demo_Indices]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 1;
GO
USE [Demo_Indices]
GO
/****** Object:  Table [dbo].[ClusteredTable]    Script Date: 25/04/2023 01:38:56 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ClusteredTable](
	[clusteredTableID] [int] IDENTITY(1,1) NOT NULL,
	[productName] [nvarchar](50) NOT NULL,
	[productNumber] [nvarchar](25) NOT NULL,
	[carrierTrackingNumber] [nvarchar](25) NULL,
	[orderQty] [smallint] NOT NULL,
	[unitPrice] [money] NOT NULL,
	[unitPriceDiscount] [money] NOT NULL,
 CONSTRAINT [PK_ClusteredTable] PRIMARY KEY NONCLUSTERED 
(
	[clusteredTableID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HeapTable]    Script Date: 25/04/2023 01:38:56 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HeapTable](
	[heapTableID] [int] IDENTITY(1,1) NOT NULL,
	[productName] [nvarchar](50) NOT NULL,
	[productNumber] [nvarchar](25) NOT NULL,
	[carrierTrackingNumber] [nvarchar](25) NULL,
	[orderQty] [smallint] NOT NULL,
	[unitPrice] [money] NOT NULL,
	[unitPriceDiscount] [money] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_HeapTable(productName, productNumber)]    Script Date: 25/04/2023 01:38:56 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_HeapTable(productName, productNumber)] ON [dbo].[HeapTable]
(
	[productName] ASC,
	[productNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Demo_Indices] SET  READ_WRITE 
GO
