//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadTest_SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeleteOperations
    {
        public string UserName { get; set; }
        public string ServerName { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public string ExecutedQuery { get; set; }
    }
}
